### ISSUE TITLE
BlueROV2 CAD files missing

### ISSUE THREAD

**Issue by markwilkie** [bluerobotics/bluerobotics.github.io#12]
The links to the CAD files here (http://docs.bluerobotics.com/brov2/) don't actually point to any CAD files.

**Comment by rjehangir** [comment]
Hi Mark,

Thanks for pointing that out. We've got the files on GrabCAD and we're going to change the page to point to those files instead so that our servers don't get hammered with the relatively large file size.

Here's the link where you can download them: https://grabcad.com/library/bluerov2-1

-Rust
